repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
    - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
      rev: v9.1.0
      hooks:
          - id: commitlint
            stages: [commit-msg]
            additional_dependencies: ["@commitlint/config-conventional"]
    - repo: local
      hooks:
          - id: lint
            name: Lint
            entry: bash -c 'pnpm run lint:fix'
            language: system
